---
codecov:
  bot: "codecov-io"
  max_report_age: 24
  disable_default_path_fixes: false
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
coverage:
  precision: 2
  round: down
  range: "80...100"
