---
name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - platform-engineering
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "[e.g. A clear and concise description of what the bug is, including steps to reproduce]"
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: action-version
    attributes:
      label: Action Version
      description: What version of the action are you running?
      placeholder: "[e.g. 1.0.0]"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: Add any other information about the problem here.
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: Please Confirm the following before submitting the issue.
      options:
        - label: I have verified that this issue is not a duplicate.
          required: true
