---
name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - platform-engineering
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like to see [...]"
    validations:
      required: true
  - type: textarea
    id: alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Alternative approaches could include [...]"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Additional information that might be helpful [...]"
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      description: Please confirm the following before submitting the feature request.
      options:
        - label: I have verified that this feature request is not a duplicate.
          required: true
        - label: I have considered if this feature aligns with the project's goals and scope.
          required: true
